//
// Generated file, do not edit! Created by nedtool 4.6 from pack.msg.
//

#ifndef _PACK_M_H_
#define _PACK_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>pack.msg:21</tt> by nedtool.
 * <pre>
 * message packmsg
 * {
 *     string src;
 *     string dest;
 * }
 * </pre>
 */
class packmsg : public ::cMessage
{
  protected:
    opp_string src_var;
    opp_string dest_var;

  private:
    void copy(const packmsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const packmsg&);

  public:
    packmsg(const char *name=NULL, int kind=0);
    packmsg(const packmsg& other);
    virtual ~packmsg();
    packmsg& operator=(const packmsg& other);
    virtual packmsg *dup() const {return new packmsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSrc() const;
    virtual void setSrc(const char * src);
    virtual const char * getDest() const;
    virtual void setDest(const char * dest);
};

inline void doPacking(cCommBuffer *b, packmsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, packmsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PACK_M_H_

